FROM clearlinux/python

RUN mkdir -p /workspace
WORKDIR /workspace

COPY app ./
COPY static ./
COPY templates ./
COPY embeddings.pickle ./
COPY keys_dict.json ./
COPY requirements.txt ./

RUN pip install -r requirements.txt

CMD ["python", "app/main.py"]
